### ISSUE TITLE
ShaguNotify for tbc

### ISSUE THREAD

**Issue by Macumbafeh** [shagu/ShaguNotify#1]
OMG ! This addon is just awesome !

If i change the number to 20400 in the .toc file it will work for TBC?

Ty !

**Comment by shagu** [comment]
You don't need to. Just rename the folder to `ShaguNotify-tbc` and it should work ;)

**Comment by shagu** [comment]
I have just updated the install instructions in the README.md :)
https://github.com/shagu/ShaguNotify/commit/e113d85812df8b56c0f5309ac44254f3fdccd395

**Comment by Macumbafeh** [comment]
Ty you are the best.
